### ISSUE TITLE
VPN Issues when accessing the site

### ISSUE THREAD

**Issue by renc-curvelabs** [PrimeDAO/prime-launch-dapp#681]

**Comment by renc-curvelabs** [comment]
Mullvad

**Comment by renc-curvelabs** [comment]
_"Works with VPN on for various territories. France, US for example, but not for UK
Using Brave"_ - As reported

**Comment by renc-curvelabs** [comment]
Gilad is getting an error with Opera's built in VPN

**Comment by BartuCulha** [comment]
Used Opera VPN set location to "Americas"
"Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
vendors~556c66f2.0b29e9b84322311f6adb.chunk.js:sourcemap:18 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ vendors~556c66f2.0b29e9b84322311f6adb.chunk.js:sourcemap:18
launch.prime.xyz/:1 Access to XMLHttpRequest at 'https://api.coingecko.com/api/v3/coins/list' from origin 'https://launch.prime.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vendors~556c66f2.0b29e9b84322311f6adb.chunk.js:sourcemap:16 ERROR [Prime Launch] Error initializing the app
Error: Network Error
    at LYNF.e.exports (https://launch.prime.xyz/vendors~2a42e354.fbc85d1d6292f7d4b3c5.chunk.js:1:5807)
    at XMLHttpRequest.d.onerror (https://launch.prime.xyz/vendors~2a42e354.fbc85d1d6292f7d4b3c5.chunk.js:1:34025)
t.error @ vendors~556c66f2.0b29e9b84322311f6adb.chunk.js:sourcemap:16
api.coingecko.com/api/v3/coins/list:1 Failed to load resource: net::ERR_FAILED
vendors~dab50aa4.75528ec6baabcf4f150d.chunk.js:sourcemap:1 @metamask/detect-provider: Unable to detect window.ethereum.
i @ vendors~dab50aa4.75528ec6baabcf4f150d.chunk.js:sourcemap:1"
